"""Add rank to Recommendation

Revision ID: 66d37bc5ab3f
Revises: adbbc123bc42
Create Date: 2025-07-06 03:06:12.720094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d37bc5ab3f'
down_revision = 'adbbc123bc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
