"""Add cart table

Revision ID: 6a8536c017a9
Revises: b290d2a248eb
Create Date: 2025-06-24 06:34:35.250644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a8536c017a9'
down_revision = 'b290d2a248eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmall_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('item_id'))

    op.drop_table('tmall_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.create_unique_constraint(None, ['item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('item_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False)

    op.create_table('tmall_products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('image_url', mysql.TEXT(), nullable=True),
    sa.Column('local_image_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('shop_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('shop_rating', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('crawled_at', mysql.DATETIME(), nullable=True),
    sa.Column('item_id', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tmall_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('item_id'), ['item_id'], unique=True)

    # ### end Alembic commands ###
